baseURL = 'https://tomcat0x42.me'
languageCode = 'en-us'
title = 'Tomcat0x42'
enableEmoji = true
enableRobotsTXT = true
theme = 'nostyleplease'
staticDir = ['pkgs', 'assets']

[outputs]
  home = ["HTML", "RSS"]

[permalinks]
  # posts = ":title"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  favicon = 'favicon.ico'
  cover = 'cover.png'
  description = "Tomcat0x42's personal blog"
  [params.theme_config]
    appearance = "dark"
    back_home_text = ".."
    date_format = "2006-01-02"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'modus-vivendi'
    tabWidth = 2
